<div class="jumbotron">
    <h1>Sobre o Projeto</h1>    
    <p class="lead">
        Esse projeto consiste em uma simples Agenda de Contatos Online,
        desenvolvida no ZendFramework 2.
    </p>
    
    <h3>Ferramentas utilizadas:</h3>
    <ul class="list-inline">
        <li><span class="label label-primary">Ubuntu 13.10</span></li>
        <li><span class="label label-primary">Zend Framework 2</span></li>
        <li><span class="label label-primary">ZFTool</span></li>
        <li><span class="label label-primary">Composer</span></li>
        <li><span class="label label-primary">Apache 2</span></li>
        <li><span class="label label-primary">VHOST</span></li>
        <li><span class="label label-primary">PHP 5.4</span></li>
        <li><span class="label label-primary">Servidor Interno PHP 5.4</span></li>
        <li><span class="label label-primary">NetBeans 8.0 Beta</span></li>
        <li><span class="label label-primary">Git</span></li>
        <li><span class="label label-primary">GitHub</span></li>
        <li><span class="label label-primary">Boostrap</span></li>
        <li><span class="label label-primary">jQuery</span></li>
        <li><span class="label label-primary">MySql</span></li>
    </ul>
</div>
    
