<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Contato          
        </div>
    </div>
    
    <?php
    // objeto form contato
    $formContato = $this->formContato;
    // prepara elementos do formulário
    $formContato->prepare();
    //configura url formulário
    $formContato->setAttribute('action',$this->url('contatos',array('action' => 'adicionar')));    
    ?>
    
    <?php //renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formContato) ?>
    
    
    <!--<form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('contatos', array('action' => 'adicionar')); ?>">-->
        <div class="panel-body">
            <div class="form-group">
                <label for="inputNome" class="col-lg-3 col-md-3 control-label">Nome*:</label>
                <div class="col-lg-9 col-md-9">
                    <?php
                    //renderiza html input
                    echo $this->formInput($formContato->get('nome'));
                    
                    //renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formContato->get('nome'));
                    ?>
                    <!--<input type="text" name="nome" class="form-control" id="inputNome" placeholder="Nome Completo">-->
                </div>
            </div>
 
            <div class="form-group">
                <label for="inputTelefonePrincipal" class="col-lg-3 col-md-3 control-label">Tel. Principal*:</label>
                <div class="col-lg-9  col-md-9">
                    <!--<input type="text" name="telefone_principal" class="form-control" id="inputTelefonePrincipal" placeholder="Digite seu telefone principal">-->
                    <?php
                    // renderiza html input
                    echo $this->formInput($formContato->get('telefone_principal'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formContato->get('telefone_principal'));
                    ?>
                </div>
            </div>
 
            <div class="form-group">
                <label for="inputTelefoneSecundario" class="col-lg-3 col-md-3 control-label">Tel. Secundário:</label>
                <div class="col-lg-9  col-md-9">
                    <!--<input type="text" name="telefone_secundario" class="form-control" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)">-->
                    <?php
                    // renderiza html input
                    echo $this->formInput($formContato->get('telefone_secundario'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formContato->get('telefone_secundario'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
                <label for="inputCaptcha" class="col-lg-3 col-md-3 control-label">Verificação*:</label>
                <div class="col-lg-9  col-md-9" id="captcha">
                    <?php
                    // renderiza captcha
                    echo $this->formCaptcha($formContato->get('captcha'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formContato->get('captcha'));
                    ?>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <?php
            //renderiza html input hidden para id
            echo $this->formHidden($formContato->get('id'));
            //renderiza htmo input hidden csrf
            echo $this->formElement($formContato->get('security'));
            ?>
            
            <button type="submit" class="btn btn-primary">Salvar Contato</button>
            <a href="<?php echo $this->url('contatos'); ?>" class="btn btn-default">Voltar</a>
        </div>
    <?php //renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
    <!--</form>-->
</div>