<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?php echo $this->doctype(); ?>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        
        <!--<title></title>-->
        <?php 
            $NAME_APPLICATION = 'Agenda de Contatos Online';
            echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
            ;
        ?>
        
        <!--Meta Head-->
        <?php
            echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ;
        ?>
        
        <!--Styles-->
        <?php
            echo $this
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/styles.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ;
        ?>
        

        
    </head>
    <body>
        <div class="container">
            <div class="header">
                <ul class="nav nav-pills pull-right">
                    <?php
                    //definindo as urls do index
                    $url_home  = $this->url('home');
                    $url_sobre = $this->url('sobre');
                    ?>
<!--                    <li class="active"><a href="#">Início</a></li>-->
                    <li <?php echo $this->menuAtivo($url_home); ?>>
                        <a href="<?php echo $url_home; ?>">Início</a>
                    </li>
<!--                    <li><a href="#">Sobre</a></li>-->
                    <li <?php echo $this->menuAtivo($url_sobre);?>>
                        <a href="<?php echo $url_sobre; ?>">Sobre</a>
                    </li>
                </ul>
                <h3 class="text-muted"><?php echo $NAME_APPLICATION; ?></h3>
            </div>
            
            <?php echo $this->mensagem(); ?>
            <br>
            <div class="row marketing">
                <?php echo $this->content;  ?> <!-- não carrega o conteúdo do index -->
            </div>
            
            <div class="footer">
                <p class="muted credit pull-left">Companhia <a href="">© 2013</a></p>
                <p class="muted credit pull-right">Desenvolvido por <a href="http://www.semid.ufma.br">Jaccozinho Corporation S/A</a>.</p>
            </div>
        </div>
        
        <!--Scripts-->
        <?php
            echo $this
                ->headScript()                
                ->prependFile($this->basePath() . '/js/repond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')    
                ->prependFile($this->basePath() . '/js/scripts.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                
            ;
            
            echo $this->inlineScript();
        ?>
    </body>
</html>